# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_end.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 708)
        MainWindow.setStyleSheet("background-color: rgb(238, 238, 236);\n"
"color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"color: rgb(238, 238, 236);")
        self.centralwidget.setObjectName("centralwidget")
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setGeometry(QtCore.QRect(42, 0, 107, 647))
        self.full_menu_widget.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout_2.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.home_btn_2.setMinimumSize(QtCore.QSize(14, 14))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon2/icon2/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon2/icon2/white_home.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn_2.setIcon(icon)
        self.home_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.usuario_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.usuario_btn_2.setMinimumSize(QtCore.QSize(14, 14))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon2/icon2/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon2/icon2/white_plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.usuario_btn_2.setIcon(icon1)
        self.usuario_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.usuario_btn_2.setCheckable(True)
        self.usuario_btn_2.setAutoExclusive(True)
        self.usuario_btn_2.setObjectName("usuario_btn_2")
        self.verticalLayout_2.addWidget(self.usuario_btn_2)
        self.veiculo_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.veiculo_btn_2.setMinimumSize(QtCore.QSize(14, 14))
        self.veiculo_btn_2.setIcon(icon1)
        self.veiculo_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.veiculo_btn_2.setCheckable(True)
        self.veiculo_btn_2.setAutoExclusive(True)
        self.veiculo_btn_2.setObjectName("veiculo_btn_2")
        self.verticalLayout_2.addWidget(self.veiculo_btn_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.full_menu_widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(14, 14))
        self.pushButton_10.setText("")
        self.pushButton_10.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setAutoExclusive(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.full_menu_widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(14, 14))
        self.pushButton_11.setText("")
        self.pushButton_11.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setAutoExclusive(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 463, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setMinimumSize(QtCore.QSize(14, 14))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon2/icon2/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_2.setIcon(icon2)
        self.exit_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn_2.setCheckable(False)
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(149, 0, 904, 618))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_4.setStyleSheet("background-color: rgb(78, 154, 6);")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(336, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(336, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_27 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_20.addWidget(self.label_27)
        self.tabela_relacoes = QtWidgets.QTableWidget(self.page)
        self.tabela_relacoes.setObjectName("tabela_relacoes")
        self.tabela_relacoes.setColumnCount(0)
        self.tabela_relacoes.setRowCount(0)
        self.verticalLayout_20.addWidget(self.tabela_relacoes)
        self.widget_17 = QtWidgets.QWidget(self.page)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_locar_relacao_redirect = QtWidgets.QPushButton(self.widget_17)
        self.btn_locar_relacao_redirect.setObjectName("btn_locar_relacao_redirect")
        self.horizontalLayout_14.addWidget(self.btn_locar_relacao_redirect)
        self.btn_editar_relacao_redirect = QtWidgets.QPushButton(self.widget_17)
        self.btn_editar_relacao_redirect.setObjectName("btn_editar_relacao_redirect")
        self.horizontalLayout_14.addWidget(self.btn_editar_relacao_redirect)
        self.btn_excluir_relacao_redirect = QtWidgets.QPushButton(self.widget_17)
        self.btn_excluir_relacao_redirect.setObjectName("btn_excluir_relacao_redirect")
        self.horizontalLayout_14.addWidget(self.btn_excluir_relacao_redirect)
        self.verticalLayout_20.addWidget(self.widget_17)
        self.stackedWidget.addWidget(self.page)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setEnabled(True)
        self.page_17.setObjectName("page_17")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_17)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_6 = QtWidgets.QLabel(self.page_17)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_25.addWidget(self.label_6)
        self.tabela_veiculos = QtWidgets.QTableWidget(self.page_17)
        self.tabela_veiculos.setObjectName("tabela_veiculos")
        self.tabela_veiculos.setColumnCount(0)
        self.tabela_veiculos.setRowCount(0)
        self.verticalLayout_25.addWidget(self.tabela_veiculos)
        self.widget_16 = QtWidgets.QWidget(self.page_17)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_cadastrar_veiculo_redirect = QtWidgets.QPushButton(self.widget_16)
        self.btn_cadastrar_veiculo_redirect.setObjectName("btn_cadastrar_veiculo_redirect")
        self.horizontalLayout_13.addWidget(self.btn_cadastrar_veiculo_redirect)
        self.btn_editar_veiculo_redirect = QtWidgets.QPushButton(self.widget_16)
        self.btn_editar_veiculo_redirect.setObjectName("btn_editar_veiculo_redirect")
        self.horizontalLayout_13.addWidget(self.btn_editar_veiculo_redirect)
        self.btn_excluir_veiculo_redirect = QtWidgets.QPushButton(self.widget_16)
        self.btn_excluir_veiculo_redirect.setObjectName("btn_excluir_veiculo_redirect")
        self.horizontalLayout_13.addWidget(self.btn_excluir_veiculo_redirect)
        self.verticalLayout_25.addWidget(self.widget_16)
        self.stackedWidget.addWidget(self.page_17)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.tabela_usuarios = QtWidgets.QTableWidget(self.page_2)
        self.tabela_usuarios.setObjectName("tabela_usuarios")
        self.tabela_usuarios.setColumnCount(0)
        self.tabela_usuarios.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tabela_usuarios)
        self.widget_10 = QtWidgets.QWidget(self.page_2)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_cadastrar_usuario_redirect = QtWidgets.QPushButton(self.widget_10)
        self.btn_cadastrar_usuario_redirect.setObjectName("btn_cadastrar_usuario_redirect")
        self.horizontalLayout_8.addWidget(self.btn_cadastrar_usuario_redirect)
        self.btn_editar_usuario_redirect = QtWidgets.QPushButton(self.widget_10)
        self.btn_editar_usuario_redirect.setObjectName("btn_editar_usuario_redirect")
        self.horizontalLayout_8.addWidget(self.btn_editar_usuario_redirect)
        self.btn_excluir_usuario_redirect = QtWidgets.QPushButton(self.widget_10)
        self.btn_excluir_usuario_redirect.setObjectName("btn_excluir_usuario_redirect")
        self.horizontalLayout_8.addWidget(self.btn_excluir_usuario_redirect)
        self.verticalLayout_8.addWidget(self.widget_10)
        self.stackedWidget.addWidget(self.page_2)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.page_8)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.input_nome_completo = QtWidgets.QLineEdit(self.frame)
        self.input_nome_completo.setObjectName("input_nome_completo")
        self.verticalLayout_6.addWidget(self.input_nome_completo)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.input_email = QtWidgets.QLineEdit(self.frame)
        self.input_email.setObjectName("input_email")
        self.verticalLayout_6.addWidget(self.input_email)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.input_telefone = QtWidgets.QLineEdit(self.frame)
        self.input_telefone.setObjectName("input_telefone")
        self.verticalLayout_6.addWidget(self.input_telefone)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.input_cpf = QtWidgets.QLineEdit(self.frame)
        self.input_cpf.setObjectName("input_cpf")
        self.verticalLayout_6.addWidget(self.input_cpf)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.input_cep = QtWidgets.QLineEdit(self.frame)
        self.input_cep.setObjectName("input_cep")
        self.verticalLayout_6.addWidget(self.input_cep)
        self.btn_buscar_cep = QtWidgets.QPushButton(self.frame)
        self.btn_buscar_cep.setObjectName("btn_buscar_cep")
        self.verticalLayout_6.addWidget(self.btn_buscar_cep)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.input_bairro = QtWidgets.QLineEdit(self.frame)
        self.input_bairro.setObjectName("input_bairro")
        self.verticalLayout_6.addWidget(self.input_bairro)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.input_rua = QtWidgets.QLineEdit(self.frame)
        self.input_rua.setObjectName("input_rua")
        self.verticalLayout_6.addWidget(self.input_rua)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.input_numero = QtWidgets.QLineEdit(self.frame)
        self.input_numero.setObjectName("input_numero")
        self.verticalLayout_6.addWidget(self.input_numero)
        self.btn_limpar_cadastro_usuario = QtWidgets.QPushButton(self.frame)
        self.btn_limpar_cadastro_usuario.setObjectName("btn_limpar_cadastro_usuario")
        self.verticalLayout_6.addWidget(self.btn_limpar_cadastro_usuario)
        self.btn_cadastrar_usuario = QtWidgets.QPushButton(self.frame)
        self.btn_cadastrar_usuario.setObjectName("btn_cadastrar_usuario")
        self.verticalLayout_6.addWidget(self.btn_cadastrar_usuario)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_8)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.page_19)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_39 = QtWidgets.QLabel(self.page_19)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_24.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.page_19)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_24.addWidget(self.label_40)
        self.input_cpf_cliente_tela_locar_carro = QtWidgets.QLineEdit(self.page_19)
        self.input_cpf_cliente_tela_locar_carro.setObjectName("input_cpf_cliente_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.input_cpf_cliente_tela_locar_carro)
        self.label_41 = QtWidgets.QLabel(self.page_19)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_24.addWidget(self.label_41)
        self.input_placa_veiculo_tela_locar_carro = QtWidgets.QLineEdit(self.page_19)
        self.input_placa_veiculo_tela_locar_carro.setObjectName("input_placa_veiculo_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.input_placa_veiculo_tela_locar_carro)
        self.label_49 = QtWidgets.QLabel(self.page_19)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_24.addWidget(self.label_49)
        self.input_tipo_tela_locar_carro = QtWidgets.QLineEdit(self.page_19)
        self.input_tipo_tela_locar_carro.setObjectName("input_tipo_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.input_tipo_tela_locar_carro)
        self.label_42 = QtWidgets.QLabel(self.page_19)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_24.addWidget(self.label_42)
        self.input_data_tela_locar_carro = QtWidgets.QDateEdit(self.page_19)
        self.input_data_tela_locar_carro.setObjectName("input_data_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.input_data_tela_locar_carro)
        self.label_50 = QtWidgets.QLabel(self.page_19)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_24.addWidget(self.label_50)
        self.btn_calcular_tela_locar_carro = QtWidgets.QPushButton(self.page_19)
        self.btn_calcular_tela_locar_carro.setObjectName("btn_calcular_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.btn_calcular_tela_locar_carro)
        self.input_total_tela_locar_carro = QtWidgets.QLineEdit(self.page_19)
        self.input_total_tela_locar_carro.setObjectName("input_total_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.input_total_tela_locar_carro)
        self.btn_limpar_tela_locar_carro = QtWidgets.QPushButton(self.page_19)
        self.btn_limpar_tela_locar_carro.setObjectName("btn_limpar_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.btn_limpar_tela_locar_carro)
        self.btn_confirmar_tela_locar_carro = QtWidgets.QPushButton(self.page_19)
        self.btn_confirmar_tela_locar_carro.setObjectName("btn_confirmar_tela_locar_carro")
        self.verticalLayout_24.addWidget(self.btn_confirmar_tela_locar_carro)
        self.stackedWidget.addWidget(self.page_19)
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.page_20)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_47 = QtWidgets.QLabel(self.page_20)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_28.addWidget(self.label_47)
        self.input_id_tela_editar_relacao = QtWidgets.QLineEdit(self.page_20)
        self.input_id_tela_editar_relacao.setObjectName("input_id_tela_editar_relacao")
        self.verticalLayout_28.addWidget(self.input_id_tela_editar_relacao)
        self.widget_19 = QtWidgets.QWidget(self.page_20)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btn_voltar_tela_editar_relacao = QtWidgets.QPushButton(self.widget_19)
        self.btn_voltar_tela_editar_relacao.setObjectName("btn_voltar_tela_editar_relacao")
        self.horizontalLayout_16.addWidget(self.btn_voltar_tela_editar_relacao)
        self.btn_editar_tela_editar_relacao = QtWidgets.QPushButton(self.widget_19)
        self.btn_editar_tela_editar_relacao.setObjectName("btn_editar_tela_editar_relacao")
        self.horizontalLayout_16.addWidget(self.btn_editar_tela_editar_relacao)
        self.verticalLayout_28.addWidget(self.widget_19)
        self.stackedWidget.addWidget(self.page_20)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.page_21)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_48 = QtWidgets.QLabel(self.page_21)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_27.addWidget(self.label_48)
        self.input_id_tela_excluir_relacao = QtWidgets.QLineEdit(self.page_21)
        self.input_id_tela_excluir_relacao.setText("")
        self.input_id_tela_excluir_relacao.setObjectName("input_id_tela_excluir_relacao")
        self.verticalLayout_27.addWidget(self.input_id_tela_excluir_relacao)
        self.widget_18 = QtWidgets.QWidget(self.page_21)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_voltar_tela_excluir_relacao = QtWidgets.QPushButton(self.widget_18)
        self.btn_voltar_tela_excluir_relacao.setObjectName("btn_voltar_tela_excluir_relacao")
        self.horizontalLayout_15.addWidget(self.btn_voltar_tela_excluir_relacao)
        self.btn_excluir_tela_excluir_relacao = QtWidgets.QPushButton(self.widget_18)
        self.btn_excluir_tela_excluir_relacao.setObjectName("btn_excluir_tela_excluir_relacao")
        self.horizontalLayout_15.addWidget(self.btn_excluir_tela_excluir_relacao)
        self.verticalLayout_27.addWidget(self.widget_18)
        self.input_id_tela_excluir_relacao.raise_()
        self.label_48.raise_()
        self.widget_18.raise_()
        self.stackedWidget.addWidget(self.page_21)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setEnabled(True)
        self.page_18.setObjectName("page_18")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_18)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_43 = QtWidgets.QLabel(self.page_18)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_26.addWidget(self.label_43)
        self.label_45 = QtWidgets.QLabel(self.page_18)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_26.addWidget(self.label_45)
        self.input_cpf_cliente_tela_vender_carro = QtWidgets.QLineEdit(self.page_18)
        self.input_cpf_cliente_tela_vender_carro.setObjectName("input_cpf_cliente_tela_vender_carro")
        self.verticalLayout_26.addWidget(self.input_cpf_cliente_tela_vender_carro)
        self.label_44 = QtWidgets.QLabel(self.page_18)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_26.addWidget(self.label_44)
        self.input_placa_veiculo_tela_vender_carro = QtWidgets.QLineEdit(self.page_18)
        self.input_placa_veiculo_tela_vender_carro.setObjectName("input_placa_veiculo_tela_vender_carro")
        self.verticalLayout_26.addWidget(self.input_placa_veiculo_tela_vender_carro)
        self.label_46 = QtWidgets.QLabel(self.page_18)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_26.addWidget(self.label_46)
        self.btn_calcular_tela_vender_carro = QtWidgets.QPushButton(self.page_18)
        self.btn_calcular_tela_vender_carro.setObjectName("btn_calcular_tela_vender_carro")
        self.verticalLayout_26.addWidget(self.btn_calcular_tela_vender_carro)
        self.input_total_venda_tela_vender_carro = QtWidgets.QLineEdit(self.page_18)
        self.input_total_venda_tela_vender_carro.setObjectName("input_total_venda_tela_vender_carro")
        self.verticalLayout_26.addWidget(self.input_total_venda_tela_vender_carro)
        self.btn_confirmar_tela_vender_carro = QtWidgets.QPushButton(self.page_18)
        self.btn_confirmar_tela_vender_carro.setObjectName("btn_confirmar_tela_vender_carro")
        self.verticalLayout_26.addWidget(self.btn_confirmar_tela_vender_carro)
        self.stackedWidget.addWidget(self.page_18)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_6 = QtWidgets.QWidget(self.page_6)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.input_id_tela_excluir_usuario = QtWidgets.QLineEdit(self.widget_6)
        self.input_id_tela_excluir_usuario.setObjectName("input_id_tela_excluir_usuario")
        self.verticalLayout_10.addWidget(self.input_id_tela_excluir_usuario)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_voltar_tela_excluir_usuario_redirect = QtWidgets.QPushButton(self.widget_7)
        self.btn_voltar_tela_excluir_usuario_redirect.setObjectName("btn_voltar_tela_excluir_usuario_redirect")
        self.horizontalLayout_6.addWidget(self.btn_voltar_tela_excluir_usuario_redirect)
        self.btn_excluir_tela_excluir_usuario_redirect = QtWidgets.QPushButton(self.widget_7)
        self.btn_excluir_tela_excluir_usuario_redirect.setObjectName("btn_excluir_tela_excluir_usuario_redirect")
        self.horizontalLayout_6.addWidget(self.btn_excluir_tela_excluir_usuario_redirect)
        self.verticalLayout_10.addWidget(self.widget_7)
        self.verticalLayout_11.addWidget(self.widget_6)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_8 = QtWidgets.QWidget(self.page_7)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.input_id_tela_editar_usuario = QtWidgets.QLineEdit(self.widget_8)
        self.input_id_tela_editar_usuario.setObjectName("input_id_tela_editar_usuario")
        self.verticalLayout_12.addWidget(self.input_id_tela_editar_usuario)
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_voltar_tela_editar_usuario_redirect = QtWidgets.QPushButton(self.widget_9)
        self.btn_voltar_tela_editar_usuario_redirect.setObjectName("btn_voltar_tela_editar_usuario_redirect")
        self.horizontalLayout_7.addWidget(self.btn_voltar_tela_editar_usuario_redirect)
        self.btn_editar_tela_editar_usuario_redirect = QtWidgets.QPushButton(self.widget_9)
        self.btn_editar_tela_editar_usuario_redirect.setObjectName("btn_editar_tela_editar_usuario_redirect")
        self.horizontalLayout_7.addWidget(self.btn_editar_tela_editar_usuario_redirect)
        self.verticalLayout_12.addWidget(self.widget_9)
        self.verticalLayout_13.addWidget(self.widget_8)
        self.stackedWidget.addWidget(self.page_7)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_37 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_22.addWidget(self.label_37)
        self.input_id_tela_editar_veiculo = QtWidgets.QLineEdit(self.page_3)
        self.input_id_tela_editar_veiculo.setObjectName("input_id_tela_editar_veiculo")
        self.verticalLayout_22.addWidget(self.input_id_tela_editar_veiculo)
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_voltar_tela_editar_veiculo_redirect = QtWidgets.QPushButton(self.widget)
        self.btn_voltar_tela_editar_veiculo_redirect.setObjectName("btn_voltar_tela_editar_veiculo_redirect")
        self.horizontalLayout_5.addWidget(self.btn_voltar_tela_editar_veiculo_redirect)
        self.btn_editar_tela_editar_veiculo_redirect = QtWidgets.QPushButton(self.widget)
        self.btn_editar_tela_editar_veiculo_redirect.setObjectName("btn_editar_tela_editar_veiculo_redirect")
        self.horizontalLayout_5.addWidget(self.btn_editar_tela_editar_veiculo_redirect)
        self.verticalLayout_22.addWidget(self.widget)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_38 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_23.addWidget(self.label_38)
        self.input_id_tela_excluir_veiculo = QtWidgets.QLineEdit(self.page_4)
        self.input_id_tela_excluir_veiculo.setObjectName("input_id_tela_excluir_veiculo")
        self.verticalLayout_23.addWidget(self.input_id_tela_excluir_veiculo)
        self.widget_5 = QtWidgets.QWidget(self.page_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_voltar_tela_excluir_veiculo_redirect = QtWidgets.QPushButton(self.widget_5)
        self.btn_voltar_tela_excluir_veiculo_redirect.setObjectName("btn_voltar_tela_excluir_veiculo_redirect")
        self.horizontalLayout_12.addWidget(self.btn_voltar_tela_excluir_veiculo_redirect)
        self.btn_excluir_tela_excluir_veiculo_redirect = QtWidgets.QPushButton(self.widget_5)
        self.btn_excluir_tela_excluir_veiculo_redirect.setObjectName("btn_excluir_tela_excluir_veiculo_redirect")
        self.horizontalLayout_12.addWidget(self.btn_excluir_tela_excluir_veiculo_redirect)
        self.verticalLayout_23.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_36 = QtWidgets.QLabel(self.page_5)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_21.addWidget(self.label_36)
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_21.addWidget(self.label_28)
        self.input_ano_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_ano_veiculo.setObjectName("input_ano_veiculo")
        self.verticalLayout_21.addWidget(self.input_ano_veiculo)
        self.label_29 = QtWidgets.QLabel(self.page_5)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_21.addWidget(self.label_29)
        self.input_km_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_km_veiculo.setObjectName("input_km_veiculo")
        self.verticalLayout_21.addWidget(self.input_km_veiculo)
        self.label_30 = QtWidgets.QLabel(self.page_5)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_21.addWidget(self.label_30)
        self.input_cambio_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_cambio_veiculo.setObjectName("input_cambio_veiculo")
        self.verticalLayout_21.addWidget(self.input_cambio_veiculo)
        self.label_31 = QtWidgets.QLabel(self.page_5)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_21.addWidget(self.label_31)
        self.input_carroceria_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_carroceria_veiculo.setObjectName("input_carroceria_veiculo")
        self.verticalLayout_21.addWidget(self.input_carroceria_veiculo)
        self.label_32 = QtWidgets.QLabel(self.page_5)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_21.addWidget(self.label_32)
        self.input_combustivel_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_combustivel_veiculo.setObjectName("input_combustivel_veiculo")
        self.verticalLayout_21.addWidget(self.input_combustivel_veiculo)
        self.label_33 = QtWidgets.QLabel(self.page_5)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_21.addWidget(self.label_33)
        self.input_placa_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_placa_veiculo.setObjectName("input_placa_veiculo")
        self.verticalLayout_21.addWidget(self.input_placa_veiculo)
        self.label_34 = QtWidgets.QLabel(self.page_5)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_21.addWidget(self.label_34)
        self.input_cor_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_cor_veiculo.setObjectName("input_cor_veiculo")
        self.verticalLayout_21.addWidget(self.input_cor_veiculo)
        self.label_35 = QtWidgets.QLabel(self.page_5)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_21.addWidget(self.label_35)
        self.input_chassi_veiculo = QtWidgets.QLineEdit(self.page_5)
        self.input_chassi_veiculo.setObjectName("input_chassi_veiculo")
        self.verticalLayout_21.addWidget(self.input_chassi_veiculo)
        self.btn_limpar_dados_veiculo = QtWidgets.QPushButton(self.page_5)
        self.btn_limpar_dados_veiculo.setObjectName("btn_limpar_dados_veiculo")
        self.verticalLayout_21.addWidget(self.btn_limpar_dados_veiculo)
        self.btn_cadastrar_veiculo = QtWidgets.QPushButton(self.page_5)
        self.btn_cadastrar_veiculo.setObjectName("btn_cadastrar_veiculo")
        self.verticalLayout_21.addWidget(self.btn_cadastrar_veiculo)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1071, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(10)
        self.exit_btn_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo_label_3.setText(_translate("MainWindow", "MENU"))
        self.home_btn_2.setText(_translate("MainWindow", "HOME"))
        self.usuario_btn_2.setText(_translate("MainWindow", "USER"))
        self.veiculo_btn_2.setText(_translate("MainWindow", "CARS"))
        self.exit_btn_2.setText(_translate("MainWindow", "EXIT"))
        self.label_27.setText(_translate("MainWindow", "TABELA RELACIONAL"))
        self.btn_locar_relacao_redirect.setText(_translate("MainWindow", "LOCAR VEICULO"))
        self.btn_editar_relacao_redirect.setText(_translate("MainWindow", "EDITAR"))
        self.btn_excluir_relacao_redirect.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_6.setText(_translate("MainWindow", "VEICULOS"))
        self.btn_cadastrar_veiculo_redirect.setText(_translate("MainWindow", "CADASTRAR"))
        self.btn_editar_veiculo_redirect.setText(_translate("MainWindow", "EDITAR"))
        self.btn_excluir_veiculo_redirect.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_7.setText(_translate("MainWindow", "USUARIOS"))
        self.btn_cadastrar_usuario_redirect.setText(_translate("MainWindow", "CADASTRAR"))
        self.btn_editar_usuario_redirect.setText(_translate("MainWindow", "EDITAR"))
        self.btn_excluir_usuario_redirect.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_8.setText(_translate("MainWindow", "CADASTRO DE USUARIOS"))
        self.label.setText(_translate("MainWindow", "NOME COMPLETO"))
        self.label_2.setText(_translate("MainWindow", "EMAIL"))
        self.label_3.setText(_translate("MainWindow", "TELEFONE"))
        self.label_5.setText(_translate("MainWindow", "CPF "))
        self.label_9.setText(_translate("MainWindow", "CEP"))
        self.btn_buscar_cep.setText(_translate("MainWindow", "BUSCAR"))
        self.label_10.setText(_translate("MainWindow", "BAIRRO"))
        self.label_11.setText(_translate("MainWindow", "RUA"))
        self.label_12.setText(_translate("MainWindow", "NUMERO"))
        self.btn_limpar_cadastro_usuario.setText(_translate("MainWindow", "LIMPAR"))
        self.btn_cadastrar_usuario.setText(_translate("MainWindow", "CONFIRMAR"))
        self.label_39.setText(_translate("MainWindow", "LOCAR CARRO"))
        self.label_40.setText(_translate("MainWindow", "CPF"))
        self.label_41.setText(_translate("MainWindow", "PLACA"))
        self.label_49.setText(_translate("MainWindow", "TIPO"))
        self.label_42.setText(_translate("MainWindow", "LIMITE"))
        self.label_50.setText(_translate("MainWindow", "TOT"))
        self.btn_calcular_tela_locar_carro.setText(_translate("MainWindow", "CALCULAR"))
        self.btn_limpar_tela_locar_carro.setText(_translate("MainWindow", "LIMPAR"))
        self.btn_confirmar_tela_locar_carro.setText(_translate("MainWindow", "CONFIRMAR"))
        self.label_47.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_editar_relacao.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_editar_tela_editar_relacao.setText(_translate("MainWindow", "EDITAR"))
        self.label_48.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_excluir_relacao.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_excluir_tela_excluir_relacao.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_43.setText(_translate("MainWindow", "VENDER CARRO"))
        self.label_45.setText(_translate("MainWindow", "CPF do cliente"))
        self.label_44.setText(_translate("MainWindow", "Placa do veiculo"))
        self.label_46.setText(_translate("MainWindow", "TOTAL"))
        self.btn_calcular_tela_vender_carro.setText(_translate("MainWindow", "CALCULAR VENDA"))
        self.btn_confirmar_tela_vender_carro.setText(_translate("MainWindow", "CONFIRMAR"))
        self.label_4.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_excluir_usuario_redirect.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_excluir_tela_excluir_usuario_redirect.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_14.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_editar_usuario_redirect.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_editar_tela_editar_usuario_redirect.setText(_translate("MainWindow", "EDITAR"))
        self.label_37.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_editar_veiculo_redirect.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_editar_tela_editar_veiculo_redirect.setText(_translate("MainWindow", "EDITAR"))
        self.label_38.setText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_voltar_tela_excluir_veiculo_redirect.setText(_translate("MainWindow", "VOLTAR"))
        self.btn_excluir_tela_excluir_veiculo_redirect.setText(_translate("MainWindow", "EXCLUIR"))
        self.label_36.setText(_translate("MainWindow", "CADASTRO DE VEICULOS"))
        self.label_28.setText(_translate("MainWindow", "ANO DO VEICULO"))
        self.label_29.setText(_translate("MainWindow", "KILOMETRAGEM"))
        self.label_30.setText(_translate("MainWindow", "CAMBIO"))
        self.label_31.setText(_translate("MainWindow", "CARROCERIA"))
        self.label_32.setText(_translate("MainWindow", "COMBUSTIVEL"))
        self.label_33.setText(_translate("MainWindow", "PLACA"))
        self.label_34.setText(_translate("MainWindow", "COR"))
        self.label_35.setText(_translate("MainWindow", "CHASSI"))
        self.btn_limpar_dados_veiculo.setText(_translate("MainWindow", "LIMPAR"))
        self.btn_cadastrar_veiculo.setText(_translate("MainWindow", "CONFIRMAR"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

